eye_tracking:
  center: {h: 0.5, w: 0.5}
pau2motors:
  topics: {eyes_pau: EyeTurn-R;EyeTurn-L;Eyes-Up-Down, head_pau: Smile_R;Smile_L,
    lips_pau: Jaw_Up_Down, neck_pau: Upper_Gimbal_L;Upper_Gimbal_R;Lower_Gimbal_L;Lower_Gimbal_R;Neck_Rotation,
    no_pau: EyeTurn-R;EyeTurn-L;Eyes-Up-Down}
webui:
  speech_recognition: webspeech
  operator_suggestions:
    - 'How is it going?'
    - "I'm a humanoid robot"
  attention_regions:
    main: {label: 'Presenter', color: '#D9544F'}
    audience: {label: 'Audience', color: '#5BB85D'}
    specific: {label: 'Other', color: '#6CADD3'}

botname: sophia

voice_en: festival:cmu_us_slt_arctic_hts
voice_zh: festival:cmu_us_slt_arctic_hts

chatbot:
  chatbot_url: http://localhost:8001
